sudo: required
services:
  - docker

before_install:
  - docker build -t haseebafsar/smart-charging -f Dockerfile.dev .

script:
  - docker run -e CI=true haseebafsar/smart-charging npm run test

deploy:
  provider: elasticbeanstalk
  region:  "us-east-1"
  app: "smart-charging"
  env: "SmartCharging-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-771111508342"
  bucket_path: "smart-charging"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"